include:
  - local: "/includes/docker.yml"
  - local: "/includes/vault.yml"
  - local: "/includes/rules.yml"

default:
  image: alpine:latest
#  tags:
#    - ADD_CUSTOM_TAG_HERE

cache:
  paths:
    - .m2/repository/
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  PROJECT_NAME: demarches-simplifiees-bn
  PROJECT_ORGANISATION: LAB-MI
  PROJECT_PATH: ${PROJECT_ORGANISATION}-${PROJECT_NAME}
  REGISTRY_URL: "${QUAY_ROOT_URL}/${PROJECT_PATH}"


stages:
  - read-secret
  - quality-app
  - build-app
  - docker-test
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret


docker-test:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: demarches-simplifiees-bn
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  extends:
    - .buildah:test

docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: demarches-simplifiees-bn
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .buildah:build
